mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('online_judge/',include('online_judge.urls')),
    path('admin/',admin.site.urls)
]

online_judge/urls.py
from django.urls import path
from . import views

app_name = 'online_judge'
urlpatterns = [
    # /online_judge/
    path('login', views.user_login, name='user_login'),
    # /online_judge/home
    path('home', views.home, name='home'),
    # /online_judge/problem/id
    path('problem/<int:problem_id>', views.submission, name='submission'),
    # /online_judge/signup
    path('signup', views.signup, name='signup'),
    # /online_judge/logout
    path('logout', views.user_logout, name='logout')
]

online_judge/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username


class Problem(models.Model):
    problemId = models.IntegerField(primary_key=True)
    title = models.CharField(null=False, max_length=200)
    description = models.CharField(null=False, max_length=2000)
    difficulty = models.CharField(null=False, max_length=10)
    solved = models.BooleanField(default=False)
    score = models.IntegerField(default=0)
    topic = models.CharField(null=False, max_length=30)

    def __str__(self):
        return self.title


class Testcase(models.Model):
    problemId = models.ForeignKey(Problem, on_delete=models.CASCADE)
    input = models.CharField(null=False, max_length=1000)
    output = models.CharField(null=False, max_length=1000)

    def __str__(self):
        return self.problemId.title


class Submission(models.Model):
    problemId = models.ForeignKey(Problem, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.timezone)
    verdict = models.BooleanField()

online_judge/forms.py
from django import forms
from django.contrib.auth.models import User


# Create your forms here.

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter username'}
    ), required=True, max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email Id'}
    ), required=True, max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter password'}
    ), required=True, max_length=50)

    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm password'}
    ), required=True, max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm password does not match"
            )

online_judge/views.py
# Create your views here.
import os

from django.contrib.auth import login, authenticate, logout

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
import subprocess
from .models import Problem
from .forms import UserForm


def user_logout(request):
    # del request.session['user_id']
    request.session.flush()
    logout(request)
    return user_login(request)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                problems = Problem.objects.all()
                return render(request, 'pages/home.html', {'user': user, 'problems': problems})
            else:
                return HttpResponse("Account not active")
        else:
            print("Tried login and failed")
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'pages/login.html', {})


def signup(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True
        else:
            print(user_form.errors)

        if registered:
            problems = Problem.objects.all()
            return render(request, 'pages/home.html', {"user": user, 'problems': problems})

    else:
        user_form = UserForm()

    return render(request, 'pages/signup.html', {"user_form": user_form})


def home(request):
    problems = Problem.objects.all()
    return render(request, 'pages/home.html', {'problems': problems})


def submission(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)
    compiled = False
    code_text = ""
    if request.method == "POST":
        verdict = False
        compiled = True
        user = request.user
        code_text = request.POST['code']

        f = open(f"codes/{user.id}_{problem_id}.cpp", "w")
        f.write(code_text)
        f.close()

        f = open(f"codes/inputs/{problem_id}.txt", 'r')
        input_text = f.read()
        f.close()

        coded_input_text = []
        with open(f"codes/inputs/{problem_id}.txt") as f:
            coded_input_text = [x.rstrip() for x in f]

        print(coded_input_text)
        f = open(f"codes/outputs/{problem_id}.txt", "r")
        expected_output = f.read().strip()

        # subprocess.run(['docker', 'ps'])
        subprocess.run(['docker', 'cp', f'codes/{user.id}_{problem_id}.cpp', 'e45a78592bed:/a.cpp'], shell=True,
                       capture_output=True)
        output = subprocess.run(['docker', 'exec', 'e45a78592bed', 'g++', 'a.cpp'], shell=True,
                                capture_output=True, text=True)

        if os.path.exists(f"codes/{user.id}_{problem_id}.cpp"):
            os.remove(f"codes/{user.id}_{problem_id}.cpp")
        else:
            print("The file does not exist")

        print(output.stderr)

        if output.returncode == 0:
            out = subprocess.run(['docker', 'exec', '-i', 'e45a78592bed', './a.out'], shell=True, capture_output=True,
                                 text=True, input=input_text)
            print(out)
            subprocess.run(['docker', 'exec', 'e45a78592bed', 'rm', '-rf', 'a.out'], shell=True)
            subprocess.run(['docker', 'exec', 'e45a78592bed', 'rm', '-rf', 'a.cpp'], shell=True)

            with open(f"codes/outputs/{user.id}_{problem_id}.txt", "w") as f:
                f.write(out.stdout)

            with open(f"codes/outputs/{user.id}_{problem_id}.txt", "r") as f:
                your_output = f.read().strip()

            if os.path.exists(f"codes/outputs/{user.id}_{problem_id}.txt"):
                os.remove(f"codes/outputs/{user.id}_{problem_id}.txt")
            else:
                print("The file does not exist")



            print(input_text)
            print(expected_output)
            print(your_output)

            if len(your_output) != len(expected_output):
                print("length are not equal")
            else:
                for i in range(len(your_output)):
                    if your_output[i] != expected_output[i]:
                        print("Character mismatch")

            verdict = (your_output == expected_output)
            print(verdict)

            return render(request, 'pages/submission.html', {'problem': problem,
                                                             'compiled': compiled,
                                                             'input_text': coded_input_text,
                                                             'return_code': output.returncode,
                                                             'expected_output': expected_output,
                                                             'your_output': your_output,
                                                             'verdict': verdict,
                                                             'code_text': code_text
                                                             })
        return render(request, 'pages/submission.html', {'problem': problem,
                                                         'compiled': compiled,
                                                         'input_text': coded_input_text,
                                                         'return_code': output.returncode,
                                                         'expected_output': expected_output,
                                                         'error_message': output.stderr,
                                                         'code_text': code_text
                                                         })

    return render(request, 'pages/submission.html', {'problem': problem, 'compiled': compiled,
                                                     'code_text': code_text})

online_judge/templates/pages/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        #solve {
            text-decoration: none;
            color: white;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">ONLINE JUDGE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse align-items-right mx-2" id="navbarScroll">
            <div class="d-flex">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="home">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="profile">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="signup">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="row mt-2">
        <div class="list-group col-3 bg-light">
            <div class="" style="padding: 2em;">
                <h6 class="h6">SORT BY TOPIC:</h6>
                <a class="list-group-item list-group-item-action" href="#list-item-1">Dynammic Programing</a>
                <a class="list-group-item list-group-item-action" href="#list-item-2">Stack & Queue</a>
                <a class="list-group-item list-group-item-action" href="#list-item-3">Binary Tree</a>
                <a class="list-group-item list-group-item-action" href="#list-item-4">Backtracking</a>
            </div>
            <div class="" style="padding: 2em;">
                <h6 class="h6">SORT BY DIFFICULTY:</h6>
                <a class="list-group-item list-group-item-action" href="#list-item-1">Basic</a>
                <a class="list-group-item list-group-item-action" href="#list-item-2">Easy</a>
                <a class="list-group-item list-group-item-action" href="#list-item-3">Medium</a>
                <a class="list-group-item list-group-item-action" href="#list-item-4">Hard</a>
            </div>
        </div>
        <div class="col-9" style="height:500px;overflow: scroll;">
            {% for problem in problems %}
            <div class=" row border-bottom border-3 mx-2">
                <div class=" col-8 ">
                    <h5 class="h5 text-muted my-2 ">{{ problem.title }}</h5>
                    <p class="text-muted ">Topic : {{ problem.topic }}</p>
                </div>
                <div class=" col-4 ">
                    <div class="d-grid gap-2 my-2 mx-2 ">
                        <button class="btn btn-success " type="button "><b><a id="solve" href="problem/{{problem.problemId}}">Solve Problem</a></b></button>
                    </div>
                    <div>
                        <div class="row ">
                            <div class="col-6 " style="text-align: center; ">
                                <p class=" text-muted " style="display: inline; ">{{ problem.difficulty }}</p>
                            </div>
                            <div class="col-6 " style="text-align: center; ">
                                <p class=" text-muted " style="display: inline; ">10K</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>

</body>

</html>

online_judge/templates/pages/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Login|Online Judge</title>
    <style>
        #signupButton {
            text-decoration: none;
            color: red;
        }
        
        #signupButton:hover {
            color: white;
        }
        
        #admin {
            text-decoration: none;
            color: red;
        }
        
        #admin:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <section class="h-100 gradient-form" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="row mt-4">
                                    <div class="col-8"></div>
                                    <div class="col-4">
                                        <a id="admin" href="/admin" class=" ">Admin login</a>
                                    </div>
                                </div>
                                <div class="card-body p-md-5 mx-md-4 ">
                                    <div class="text-center ">
                                        <h4 class="mt-1 mb-5 pb-1 ">ONLINE JUDGE PROJECT</h4>
                                    </div>

                                    <form role="form " enctype="multipart/form-data " method="post">
                                        {% csrf_token %}
                                        <p>Please login to your account</p>

                                        <div class="form-outline mb-4 ">
                                            <label class="form-label " for="form2Example11 ">Username</label>
                                            <input name="username" type="text" id="form2Example11 " class="form-control" placeholder="Username"/>
                                        </div>

                                        <div class="form-outline mb-4 ">
                                            <label class="form-label " for="form2Example22 ">Password</label>
                                            <input name="password" type="password" id="form2Example22 " class="form-control " />
                                        </div>

                                        <div class="text-center pt-1 mb-5 pb-1 ">
                                            <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3 " type="submit ">Login</button>
                                        </div>
                                    </form>
                                    <div>
                                        <div class="d-flex align-items-center justify-content-center pb-4 ">
                                            <p class="mb-0 me-2 ">Don't have an account?</p>
                                            <button type="button " class="btn btn-outline-danger "><a href="signup " id="signupButton">Create new</a></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 bg-dark d-flex align-items-center ">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4 ">
                                    <h4 class="mb-4 ">ONLINE JUDGE</h4>
                                    <p class="small mb-0 ">Online judge for programmers, where they can solve problems and submit there code for evaluation in different programming languages.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

online_judge/templates/pages/signup.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>

    <title>Signup | Online Judge</title>
    <style>
        body {
            background-size: cover;
            padding: 2em;
            background-color: #ffff;
        }
        
        *[role="form"] {
            max-width: 530px;
            padding: 15px;
            margin: 0 auto;
            border-radius: 0.3em;
            background-color: #eee;
        }
        
        *[role="form"] h2 {
            font-family: 'Open Sans', sans-serif;
            font-size: 40px;
            font-weight: 600;
            color: #000000;
            margin-top: 5%;
            text-align: center;
            text-transform: uppercase;
            letter-spacing: 4px;
        }
    </style>
</head>

<body>
    <div class="container">
        <form role="form" enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <div class="card-header text-center form-group">
							<h3 class="card-title title-up ">Sign Up</h3>

                {{ user_form}}


            <button type="submit" class="btn btn-round bg-transparent border">Sign Up</button>
                  <a href="login">login</a>
              </div>
          </form>

    </div>
    <script>
        $(function() {
            $.validator.setDefaults({
                highlight: function(element) {
                    $(element)
                        .closest('.form-group')
                        .addClass('has-error')
                },
                unhighlight: function(element) {
                    $(element)
                        .closest('.form-group')
                        .removeClass('has-error')
                }
            });

            $.validate({
                    rules: {
                        password: "required ",
                        birthDate: "required ",
                        email: {
                            required: true,
                            email: true
                        }
                    },
                    messages: {
                        email: {
                            required: true,
                            email: true
                        }
                    },
                    password: {
                        required: " Please enter password "
                    },
                    email: {
                        required: ' Please enter email',
                        email: ' Please enter valid email'
                    },
                }

            );
        });
    </script>
</body>

</html>

online_judge/templates/pages/submission.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        window.onload = function(){
                            document.getElementById('outputWindow').click();
                        }
    </script>
    <title>Submission Page</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">ONLINE JUDGE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse align-items-right mx-2" id="navbarScroll">
            <div class="d-flex">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/online_judge/home">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="profile">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/online_judge/logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/online_judge/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/online_judge/signup">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid ">
        <div class="row my-3 ">
            <div class="col-4 bg-light " style="overflow: scroll;height:600px ">
                <div class="card " style="border: None; ">
                    <div class="card-body ">
                        <h5 class="card-title "><strong>{{ problem.title }}</strong></h5>
                        <div class="row">
                            <div class="col-6">
                                <h6 class="card-subtitle mb-2 text-muted " style="display: inline;">Difficulty : {{ problem.difficulty }}</h6>
                            </div>
                            <div class="col-6">
                                <h6 class="card-subtitle mb-2 text-muted " style="display: inline;">Submissions : 10k</h6>
                            </div>
                        </div>
                        <br class="">
                        <h6 class="card-subtitle mb-2 text-muted ">Points : {{ problem.score }}</h6>
                    </div>
                </div>
                <div class="container-fluid bg-light ">
                    <p class=" "><strong>Description:</strong></p>
                    <p class=" ">{{ problem.description }}</p>
                </div>
                {% for testcase in problem.testcase_set.all %}
                <div class="card " style="border: None; ">
                    <div class="card-body ">
                        <h5 class="card-title ">Testcase</h5>
                        <h6 class="card-subtitle mb-2 ">Input:</h6>
                        <h6 class="card-subtitle mb-2 text-muted ">{{ testcase.input }}</h6>
                        <h6 class="card-subtitle mb-2">Output:</h6>
                        <h6 class="card-subtitle mb-2 text-muted ">{{ testcase.output }}</h6>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-8 ">
                <div class="container-fluid bg-light ">
                    <h3 class="text-center mb-4 opacity-h ">CODE</h3>
                    <div class="row ">
                        <div class="col-lg-7 ">
                            Language
                            <select name="language " id="id_language ">
                              <option value=" ">---------</option>
                              <option value="54 " selected>GNU G++17 7.3.0</option>

                              <option value="59 ">Microsoft Visual C++ 2017</option>

                              <option value="61 ">GNU G++17 9.2.0 (64 bit, msys 2)</option>
                        </select>
                        </div>
                    </div>
                    <div class="form-outline my-4">
                        <form role="form" enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            <textarea name="code" class="form-control " rows="15">{{ code_text }}</textarea>
                            <button class="btn btn-success btn-md my-2 " type="submit ">Submit</button>
                            {% if compiled %}
                            <button id="outputWindow" class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
                                    data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">Output Window</button>
                            <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
                              <div class="offcanvas-header">
                                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                              </div>
                              <div class="offcanvas-body">
                                <div class="card">
                                        <div class="card-body ">
                                            {% if return_code == 1 %}
                                                <h5 class="card-title" style="color : red;"><strong>Compilation Error</strong></h5>
                                            {% else %}
                                                <h5 class="card-title" style="color : green;"><strong>Compiled Successfully</strong></h5>
                                                <br>
                                                 {% if verdict %}
                                                    <h5 class="card-subtitle" style="color : green;">Accepted</h5>
                                                 {% else %}
                                                    <h5 class="card-subtitle" style="color : red;">Wrong Answer</h5>
                                                 {% endif %}
                                            {% endif %}
                                            <br>
                                            <h6 class="card-subtitle mb-2 ">Input:</h6>
                                            {% for i in input_text %}
                                            <h6 class="card-subtitle mb-2 text-muted ">{{ i }}</h6>
                                            {% endfor %}
                                            <br>
                                            <h6 class="card-subtitle mb-2">Expected Output:</h6>
                                            <h6 class="card-subtitle mb-2 text-muted ">{{ expected_output }}</h6>
                                            <br>
                                            <h6 class="card-subtitle mb-2">Your Output:</h6>
                                            {% if return_code == 1 %}
                                                <h6 class="card-subtitle mb-2 text-muted ">{{ error_message }}</h6>
                                            {% else %}
                                                <h6 class="card-subtitle mb-2 text-muted ">{{ your_output }}</h6>
                                            {% endif %}
                                        </div>
                                    </div>
                              </div>
                            </div>
                        {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>